version: '3.8'

services:
  ctf-challenge:
    image: commandinjection-ctf-challenge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    restart: unless-stopped